config/routes.rb
Flend::Application.routes.draw do

  resources :items

  root to: 'static_pages#home'

  match '/sign_in',    to: 'users#sign_in'
  match '/sign_out',   to: 'users#sign_out'
  match '/about',      to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  match '/my_account', to: 'users#show'
  match '/my_account/edit', to: 'users#edit'
  match '/dashboard',  to: 'static_pages#dashboard'

  resources :users, only: [:update]

end

app/views/layouts/_footer.html.haml
%footer.footer
	%small= 'Flend.co'
	%nav
		%ul.nav
			%li
				= link_to 'About', about_path
			%li
				= link_to 'Contact', contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
	.navbar-inner
		.container
			%nav
				#logo= 'Flend.co'
				- if @welcome_message
					#welcome_message
						= @welcome_message
				%ul.nav.pull-right
					%li
						= link_to 'Home', root_path
					- if @signed_in
						%li
							= link_to 'Request an Item', new_item_path
					%li
						= link_to 'Item Requests', items_path
					- if @signed_in
						%li
							= link_to 'Dashboard', dashboard_path
						%li
							= link_to 'My Account', my_account_path
					%li
						- unless @signed_in
							= link_to 'Sign In', sign_in_path
						- else
							= link_to 'Sign Out', sign_out_path

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
    %head
        %title= 'Flend'
        %link= stylesheet_link_tag    "application", :media => "all"
        %link= javascript_include_tag "application"
        =render 'layouts/shim'
        = yield :scripts
    %body
        =render 'layouts/header'       
        .container
            =yield
            =render 'layouts/footer'